### ISSUE TITLE
CMake Support?

### ISSUE THREAD

**Issue by Borderliner** [EionRobb/purple-instagram#10]
I have trouble compiling this on OpenSUSE Tumbleweed. It cannot find `glib.h` and other problems. Can you provide CMake support please?

**Comment by EionRobb** [comment]
Do you have the dev packages for all the deps installed? 
Can you paste here the output from the make?

**Comment by Borderliner** [comment]
I deleted the whole thing, so I'm just gonna close this issue. Sorry for the inconvenience.
