### ISSUE TITLE
Enter the six-digit code

### ISSUE THREAD

**Issue by dennisnez** [EionRobb/purple-instagram#11]
I'm not able to login, every time I try a popup text-entry window appears: "Enter the six-digit code sent to your email", but no email is sent to me. Instead instagram.com just tells me that an unusual login attempt was made, and asks if it was me, that's it.

Does it work for anyone else? :p

**Comment by Megver83** [comment]
that's strange, I just installed it like two days ago and it worked as expected, I received the verification code, introduced it, and violá

**Comment by dennisnez** [comment]
Changing the INSTAGRAM_USERAGENT "fixed" the issue for me - I wasn't even asked for a 6 digit code. Weird.

EDIT: or maybe not. after restarting pidgin, i no longer see my list of insta contacts... no error messages are given, nothing seems to happen

EDIT2: or maybe yes. It seems to be working now. I'm not sure why the contacts list didn't appear before.

**Comment by dennisnez** [comment]
Although it should be noted that others might run into this issue. Maybe it should be easier to change the user agent in the account settings, or something. I'm not sure what Instagram is doing to flag some as suspicious.
