### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by SherbetS44105** [EionRobb/purple-instagram#8]
When I added my account, there was no list of instant messages. whenever I tried to open a new dm, it would not let me send the messages. What did I do wrong?

Linux Mint 19 if it matters

**Comment by EionRobb** [comment]
Can you attach a debug log (from the buddy list, Help->Debug Window) as you try send a message?

**Comment by SherbetS44105** [comment]
after deleting and re-adding the account, I get this (with username removed):


(11:54:03) account: Connecting to account myaccount.
(11:54:03) connection: Connecting. gc = 0x56444114fc20
(11:54:03) instagram: Fetching url https://i.instagram.com/api/v1/accounts/login/
(11:54:03) instagram: With postdata ###PASSWORD REMOVED###
(11:54:03) http: Performing new request 0x564441a9bc60 to i.instagram.com.
(11:54:03) dnsquery: Performing DNS lookup for i.instagram.com
(11:54:03) dns: Wait for DNS child 4831 failed: No child processes
(11:54:03) dns: Created new DNS child 4889, there are now 1 children.
(11:54:03) dns: Successfully sent DNS request to child 4889
(11:54:03) dns: Got response for 'i.instagram.com'
(11:54:03) dnsquery: IP resolved for i.instagram.com
(11:54:03) proxy: Attempting connection to 31.13.65.52
(11:54:03) proxy: Connecting to i.instagram.com:443 with no proxy
(11:54:03) proxy: Connection in progress
(11:54:03) proxy: Connecting to i.instagram.com:443.
(11:54:03) proxy: Connected to i.instagram.com:443.
(11:54:03) nss: Handshake failed  (-12286)
(11:54:03) socket: invalid state: 3 (should be: 2)(11:54:03) http: Request 0x564441a9bc60 performed without success.
(11:54:03) instagram: Got response:

after attempting to send a message I get this response:

(11:58:41) pidgin-libnotify: Conversation Updated (UNSEEN)

I apologize for the late response, was on vacation.

**Comment by EionRobb** [comment]
The NSS error (-12286) means that there's no common ssl ciphers. What version of Pidgin are you on? If it's not 2.13 you might need to upgrade, otherwise use the NSS Preferences plugin in Tools->Plugins to change which ciphers your pidgin is enabled for

**Comment by SherbetS44105** [comment]
currently running pidgin for ubuntu 2.12, how would I go about updating?

**Comment by SherbetS44105** [comment]
after installing version 2.13.0 It worked fine. Thank you!
